const STORE_URL = "https://streetstyle.maisonlooks.com";

window.ML_PRODUCTS = [
  {
    name: "Fear of God Essentials Black Shorts",
    brand: "Fear of God",
    category: "Shorts",
    price: "¥129.6",
    note: "Relaxed black drawstring shorts for minimalist summer streetwear.",
    image: "https://cdn.maisonlooks.com/products/file-1775237311417-979972835.webp",
    url: `${STORE_URL}/en/p/fear-of-god-essentials-black-drawstring-shorts-c1af66`,
  },
  {
    name: "Nike Air Jordan 4 Black Triple Black Sneakers",
    brand: "Jordan",
    category: "Sneakers",
    price: "¥492",
    note: "Black AJ4 profile for monochrome sneaker rotations.",
    image: "https://cdn.maisonlooks.com/products/file-1775462997985-927557180.webp",
    url: `${STORE_URL}/en/p/air-jordan-4-retro-black-cat-2020-sneakers-d0e61f`,
  },
  {
    name: "Crocs Lightning McQueen Clogs Red Kids Shoes",
    brand: "Crocs",
    category: "Clogs",
    price: "¥100",
    note: "Character clogs with a bold red finish and playful styling.",
    image: "https://cdn.maisonlooks.com/products/file-1775233651965-523056073.webp",
    url: `${STORE_URL}/en/p/crocs-cars-lightning-mcqueen-clogs-for-kids-a05e7d`,
  },
  {
    name: "Nike Air Jordan 4 Retro Cement Grey Sneakers",
    brand: "Jordan",
    category: "Sneakers",
    price: "¥314.4",
    note: "Grey AJ4 find that works with cargos, denim, and hoodies.",
    image: "https://cdn.maisonlooks.com/products/file-1775232891325-112991511.webp",
    url: `${STORE_URL}/en/p/air-jordan-4-retro-sail-university-red-sneakers-d21c35`,
  },
  {
    name: "Nike x Stussy Brazil Jersey Blue",
    brand: "Nike",
    category: "Jerseys",
    price: "¥106.8",
    note: "Blue jersey pick for sport-inspired streetwear outfits.",
    image: "https://cdn.maisonlooks.com/products/file-1775229339503-407589822.webp",
    url: `${STORE_URL}/en/p/nike-x-stussy-brazil-national-team-jersey-blue-6106ce`,
  },
  {
    name: "Nike Air Force 1 White Sneakers",
    brand: "Nike",
    category: "Sneakers",
    price: "¥96",
    note: "Classic white AF1 option for everyday outfit building.",
    image: "https://cdn.maisonlooks.com/products/file-1775448340379-316502672.webp",
    url: `${STORE_URL}/en/p/nike-air-force-1-low-white-sneakers-48c196`,
  },
  {
    name: "Gucci Doraemon Graphic T-Shirt Black",
    brand: "Gucci",
    category: "T-Shirts",
    price: "¥102",
    note: "Black graphic tee with a recognizable character-led design.",
    image: "https://cdn.maisonlooks.com/products/file-1775194938366-70135788.webp",
    url: `${STORE_URL}/en/p/gucci-doraemon-collaboration-black-t-shirt-bf22b4`,
  },
  {
    name: "Supreme Grey Hoodie with White Logo",
    brand: "Supreme",
    category: "Hoodies",
    price: "¥264",
    note: "Grey logo hoodie for simple layered streetwear fits.",
    image: "https://cdn.maisonlooks.com/products/file-1775529504288-348523454.webp",
    url: `${STORE_URL}/en/p/supreme-vertical-logo-hoodie-in-grey-d0e967`,
  },
  {
    name: "Fear of God Essentials Grey Shorts",
    brand: "Fear of God",
    category: "Shorts",
    price: "¥70.8",
    note: "Soft grey shorts for relaxed gym-to-street outfits.",
    image: "https://cdn.maisonlooks.com/products/file-1775200133304-430051564.webp",
    url: `${STORE_URL}/en/p/fear-of-god-essentials-grey-drawstring-shorts-77cddd`,
  },
  {
    name: "Nike Air Jordan 13 Black Green Sneakers",
    brand: "Jordan",
    category: "Sneakers",
    price: "¥285.6",
    note: "Black and green AJ13 find for statement sneaker styling.",
    image: "https://cdn.maisonlooks.com/products/file-1775239373894-746155229.webp",
    url: `${STORE_URL}/en/p/air-jordan-13-retro-black-green-sneakers-ce283d`,
  },
  {
    name: "Polo Ralph Lauren Grey Zip-Up Hoodie",
    brand: "Polo Ralph Lauren",
    category: "Hoodies",
    price: "¥225.6",
    note: "Grey zip hoodie for preppy streetwear and casual layering.",
    image: "https://cdn.maisonlooks.com/products/file-1775521757587-340313183.webp",
    url: `${STORE_URL}/en/p/polo-ralph-lauren-grey-zip-up-hoodie-51a945`,
  },
  {
    name: "Nike Air Max Triple Black Red Sneakers",
    brand: "Nike",
    category: "Sneakers",
    price: "¥336",
    note: "Air Max silhouette with red accents for bolder sneaker boards.",
    image: "https://cdn.maisonlooks.com/products/file-1775466950090-983529670.webp",
    url: `${STORE_URL}/en/p/nike-air-max-97-red-black-sneakers-a07740`,
  },
  {
    name: "Fear of God Essentials Black Shorts",
    brand: "Fear of God",
    category: "Shorts",
    price: "¥82.8",
    note: "Alternative black Essentials shorts find at a lower listed price.",
    image: "https://cdn.maisonlooks.com/products/file-1775224962866-113131842.webp",
    url: `${STORE_URL}/en/p/fear-of-god-essentials-black-drawstring-shorts-8ea699`,
  },
  {
    name: "Stussy Black Stussy x Nike Shorts",
    brand: "Stussy",
    category: "Shorts",
    price: "¥118.8",
    note: "Black collaboration shorts for summer streetwear and sneaker fits.",
    image: "https://cdn.maisonlooks.com/products/file-1775564220768-658020385.webp",
    url: `${STORE_URL}/en/p/stussy-x-nike-black-shorts-with-white-logo-ada6df`,
  },
  {
    name: "Nike Air Jordan 4 'Metallic Silver' Sneakers",
    brand: "Jordan",
    category: "Sneakers",
    price: "¥286.8",
    note: "Metallic silver AJ4 find for clean neutral sneaker styling.",
    image: "https://cdn.maisonlooks.com/products/file-1775459793332-993567057.webp",
    url: `${STORE_URL}/en/p/air-jordan-4-retro-metallic-silver-sneakers-3fc266`,
  },
  {
    name: "Nike Air Force 1 White Rope Laces Sneakers",
    brand: "Nike",
    category: "Sneakers",
    price: "¥252",
    note: "White AF1 variation with rope laces for a custom look.",
    image: "https://cdn.maisonlooks.com/products/file-1775462939577-561746983.webp",
    url: `${STORE_URL}/en/p/nike-air-force-1-white-rope-laces-sneakers-3d7485`,
  },
  {
    name: "Acne Studios Ami Polo Shirt Navy Solid",
    brand: "Ami Paris",
    category: "Polo Shirts",
    price: "¥72",
    note: "Navy polo shirt for cleaner casual and smart streetwear looks.",
    image: "https://cdn.maisonlooks.com/products/file-1775554585331-665613117.webp",
    url: `${STORE_URL}/en/p/armani-ami-de-coeur-navy-polo-shirt-with-red-embroidery-53bb0d`,
  },
  {
    name: "Nike Shox TL Triple Black Sneakers",
    brand: "Nike",
    category: "Sneakers",
    price: "¥285.6",
    note: "Triple black Shox TL find for tech-runner sneaker outfits.",
    image: "https://cdn.maisonlooks.com/products/file-1775447388000-583923604.webp",
    url: `${STORE_URL}/en/p/nike-shox-tl-black-sneakers-30cae5`,
  },
  {
    name: "Ralph Lauren New York Polo Shirt Navy",
    brand: "Polo Ralph Lauren",
    category: "Polo Shirts",
    price: "¥128",
    note: "Navy Ralph Lauren polo for classic street-prep styling.",
    image: "https://cdn.maisonlooks.com/products/file-1775231784434-780382207.webp",
    url: `${STORE_URL}/en/p/ralph-lauren-new-york-polo-shirt-in-navy-blue-02bc8c`,
  },
  {
    name: "Van Cleef & Arpels Alhambra Black & Silver Bracelet",
    brand: "Van Cleef & Arpels",
    category: "Accessories",
    price: "¥153.6",
    note: "Black and silver bracelet for finishing minimalist outfits.",
    image: "https://cdn.maisonlooks.com/products/file-1775202029527-668033407.webp",
    url: `${STORE_URL}/en/p/van-cleef-arpels-four-leaf-clover-bracelet-in-white-gold-with-black-onyx-and-diamonds-f6dbda`,
  }
];

window.ML_CATEGORIES = [
  { name: "Sneakers", count: 8, token: "SN", copy: "Jordan, Air Force 1, Air Max, and Shox finds." },
  { name: "Shorts", count: 4, token: "SH", copy: "Fear of God, Stussy, and warm-weather streetwear." },
  { name: "Hoodies", count: 2, token: "HD", copy: "Supreme and Polo zip-up hoodie options." },
  { name: "Polo Shirts", count: 2, token: "PO", copy: "Navy polos for classic street-prep outfits." },
  { name: "T-Shirts", count: 1, token: "TS", copy: "Graphic tees with stronger search intent." },
  { name: "Jerseys", count: 1, token: "JR", copy: "Sport-inspired tops for streetwear rotations." },
  { name: "Clogs", count: 1, token: "CG", copy: "Comfort footwear and character-led finds." },
  { name: "Accessories", count: 1, token: "AC", copy: "Jewelry pieces that complete the outfit." }
];

window.ML_BRANDS = [
  { name: "Nike", copy: "Air Force 1, Air Max, Shox, jersey, and collaboration finds." },
  { name: "Jordan", copy: "High-intent AJ4 and AJ13 sneaker searches." },
  { name: "Fear of God", copy: "Essentials shorts and relaxed minimalist staples." },
  { name: "Supreme", copy: "Logo hoodie demand for streetwear spreadsheet users." },
  { name: "Polo Ralph Lauren", copy: "Zip hoodies and polos for street-prep styling." },
  { name: "Stussy", copy: "Collaboration shorts and sport-streetwear pieces." },
  { name: "Gucci", copy: "Graphic tee finds with luxury search demand." },
  { name: "Van Cleef & Arpels", copy: "Accessory search pages for bracelet intent." }
];
