"""Independent style discovery hub with usable, existing catalogue searches."""
from urllib.parse import urlencode
from find_card import e
from finds_data import ROOT

TITLE = 'Joyagoo Brand Finds | Style Routes, Categories & QC Notes'
DESCRIPTION = 'Browse brand and style routes for Joyagoo finds with category filters, QC reminders, and buying guide links.'
DISCLAIMER = 'JoyaVault is an independent discovery and research site. It is not affiliated with or endorsed by the brands mentioned.'
STYLE_ROUTES = [
    {'name': 'Sportswear', 'category': 'Clothing', 'q': 'shorts', 'label': 'Start with shorts', 'copy': 'Explore relaxed, sport-inspired outfits through shorts. Compare the cut, waistband, measurements, and intended use before adding a candidate to your shortlist.', 'qc': 'Review the selected size, visible seams, and drawstring or fastening details.'},
    {'name': 'Retro sneakers', 'category': 'Shoes', 'q': 'retro', 'label': 'Compare retro silhouettes', 'copy': 'Use shape, panel layout, and color combinations to narrow a retro sneaker direction. Keep the exact model or version separate from a general visual reference.', 'qc': 'Compare the selected size, panel details, and visible condition across both shoes.'},
    {'name': 'Streetwear hoodies', 'category': 'Clothing', 'q': 'hoodies', 'label': 'Browse hoodie records', 'copy': 'Compare pullover and zip-front ideas by proportions, layering needs, and measurements. Choose the fit you want before treating a familiar name as a reason to buy.', 'qc': 'Check the size label, requested measurements, cuffs, and selected closure.'},
    {'name': 'Designer-style bags', 'category': 'Accessories', 'q': 'bags', 'label': 'Explore bag shapes', 'copy': 'Research bag proportions, structure, straps, and finish. This route uses design features as comparison prompts; a similar silhouette does not establish a brand relationship.', 'qc': 'Review dimensions, included straps, visible hardware, and the intended color.'},
    {'name': 'Outdoor jackets', 'category': 'Clothing', 'q': 'shell', 'label': 'Start with shell layers', 'copy': 'Explore shell-jacket ideas for an outdoor-inspired wardrobe. Clarify materials, layering room, and any performance claims on the source listing before deciding.', 'qc': 'Inspect visible closures, seams, and selected options; photos alone do not establish weather protection.'},
    {'name': 'Minimal accessories', 'category': 'Accessories', 'q': 'minimal', 'label': 'Compare minimal details', 'copy': 'Begin with restrained accessory designs and simple watch faces. Compare scale, color, and practical use rather than assuming that a small detail will suit every outfit.', 'qc': 'Check the selected finish, dimensions, and included pieces; ask about function separately.'},
]
FAQ = [
    ('Is JoyaVault affiliated with these brands?', DISCLAIMER),
    ('How should I compare brand-style finds?', 'Use a brand name, when present, as a search or comparison reference. Compare the original listing, exact options, measurements, materials described, and total budget. Similar photos or familiar names do not establish the source or quality of a product.'),
    ('What should I check in QC photos?', 'Compare the received item with your selected size, color, version, and quantity. Review visible construction, labels, included pieces, and any requested measurements. Ask your agent about unclear details before making a parcel decision; photos cannot establish every material or performance property.'),
    ('Where do I buy?', 'JoyaVault provides discovery pages and research guides. Continue to the original product source or your chosen shopping agent, such as Joyagoo, for account access, ordering, payments, warehouse questions, and shipping. Confirm the current listing details before paying.'),
]


def style_url(style):
    return '/en/best-joyagoo-finds/?' + urlencode({'category': style['category'], 'q': style['q']}) + '#finds'


def brand_output(shell):
    cards = ''.join(f'''<a class="home-category-card" data-style-route="{e(style['name'])}" href="{e(style_url(style))}"><span class="route-number">{i:02d} / {e(style['category'])}</span><h3>{e(style['name'])}</h3><p>{e(style['copy'])}</p><p><strong>QC reminder:</strong> {e(style['qc'])}</p><span class="home-text-link">{e(style['label'])} →</span></a>''' for i, style in enumerate(STYLE_ROUTES, 1))
    main = f'''<main id="main" class="home-main brand-style-page">
<section class="catalog-intro"><div class="home-shell"><nav class="catalog-breadcrumb" aria-label="Breadcrumb"><a href="/en/">Home</a><span>/</span><span aria-current="page">Brand and Style Routes</span></nav><p class="home-eyebrow">STYLE DISCOVERY / INDEPENDENT RESEARCH</p><h1>Brand and Style Routes for Joyagoo Finds</h1><p class="catalog-intro-copy">Browse brand-like, style-led, or category-led routes to research a look before opening product sources. Start with a silhouette, fit, or detail you like, then compare the specific listing and options behind each find.</p><p class="category-copy">Brand names, where they appear in search results, are references for discovery and comparison. Choose a style below to explore matching directory records and prepare your own questions.</p><p class="category-copy" id="independence-disclaimer">{e(DISCLAIMER)}</p><div class="catalog-intro-links"><a href="#style-routes">Explore six style routes ↓</a><a href="/en/joyagoo-spreadsheet/">Read the Spreadsheet Guide</a></div></div></section>
<section id="style-routes" class="home-section home-category-band"><div class="home-shell"><h2>Choose a style, then compare the details</h2><p class="home-section-note">Each card opens a category-filtered search with matching records. Results may include unverified saved listings and clearly labeled examples. Examples have no seller source; a style label is a research direction, not a product claim.</p><div class="home-category-grid">{cards}</div></div></section>
<section class="home-section home-guide-band"><div class="home-shell"><h2>Build a shortlist around what matters to you</h2><div class="category-checks"><article><h3>Describe the look</h3><p>Record the shape, fit, color, or detail that attracted you. This makes it easier to compare alternatives without relying on a name alone.</p></article><article><h3>Read the exact listing</h3><p>Keep the source URL, selected version, size, color, and quantity together. Check measurements and resolve missing information before ordering.</p></article><article><h3>Prepare QC questions</h3><p>Decide which visible details you will compare with received-item photos. Record unclear areas instead of assuming that a familiar image answers them.</p></article><article><h3>Plan beyond the product price</h3><p>Consider the parcel budget and packaging needs alongside your shortlist. Review live charges on the service you choose before paying.</p></article></div></div></section>
<section class="home-section home-shell"><h2>Continue your research</h2><div class="category-signals"><a class="home-category-card" href="/en/joyagoo-spreadsheet/"><h3>Spreadsheet Guide</h3><p>Keep source links and comparison notes organized as your shortlist develops.</p></a><a class="home-category-card" href="/en/joyagoo-buying-guide/"><h3>Buying Guide</h3><p>Understand the transition from JoyaVault research to the buying steps on Joyagoo.</p></a><a class="home-category-card" href="/en/articles/joyagoo-spreadsheet-qc-checklist/"><h3>QC Checklist</h3><p>Prepare a specific review of options, visible details, and unanswered questions.</p></a><a class="home-category-card" href="/en/articles/joyagoo-spreadsheet-shipping-planning/"><h3>Shipping Planning</h3><p>Compare packaging needs and parcel assumptions before selecting a route.</p></a></div></section>
<section class="home-section home-faq-band"><div class="home-shell faq-layout"><div><p class="home-eyebrow">RESEARCH QUESTIONS</p><h2>Brand and style FAQ</h2></div><div class="home-faq">{''.join('<details open><summary>'+e(q)+'</summary><p>'+e(a)+'</p></details>' for q,a in FAQ)}</div></div></section>
<section class="home-section home-shell home-final"><h2>Turn a style idea into a considered shortlist</h2><div class="home-actions"><a class="home-button primary" href="/en/best-joyagoo-finds/">Browse Finds</a><a class="home-button" href="/en/joyagoo-buying-guide/">Read Buying Guide</a></div></section>
</main>'''
    schema = {'@context': 'https://schema.org', '@graph': [
        {'@type': 'FAQPage', 'mainEntity': [{'@type':'Question', 'name':q, 'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in FAQ]},
        {'@type': 'BreadcrumbList', 'itemListElement': [{'@type':'ListItem','position':1,'name':'Home','item':'https://joyavault.com/en/'}, {'@type':'ListItem','position':2,'name':'Brand and Style Routes','item':'https://joyavault.com/en/brands/'}]},
    ]}
    return {ROOT / 'en/brands/index.html': shell(TITLE, DESCRIPTION, '/en/brands/', main, indexable=True, structured_data=schema)}
